FROM ev3dev/ev3dev-stretch-ev3-generic
RUN sudo apt-get update
RUN DEBIAN_FRONTEND=noninteractive \
    sudo apt-get install -y --no-install-recommends \
    ros-robot-dev \
    ros-perception-dev \
    ros-base-python-dev \
    ros-base-lisp-dev \
    rosbash \
    python-rosdep \
    ros-core-rosbuild-dev \
    ros-core-python-dev \
    ros-core-lisp-dev \
    ros-perception-python-dev \
    ros-perception-lisp-dev \
    ros-robot-python-dev \
    liburdfdom-dev \
    locate \
    rsync
